id = "io.buildpacks.stacks.jammy.static"
homepage = "https://github.com/paketo-buildpacks/jammy-static-stack"
maintainer = "Paketo Buildpacks"

platforms = ["linux/amd64", "linux/arm64"]

[build]
  description = "ubuntu:jammy with compilers and shell utilities"
  dockerfile = "./build.Dockerfile"
  gid = 1000
  shell = "/bin/bash"
  uid = 1001

  [build.args]
    architecture = "amd64"

    sources = """
    deb http://archive.ubuntu.com/ubuntu jammy main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-security main universe multiverse
    """

    packages = """\
    build-essential \
    ca-certificates \
    curl \
    git \
    jq \
    libgmp-dev \
    libssl3 \
    libyaml-0-2 \
    netbase \
    openssl \
    pkg-config \
    tzdata \
    xz-utils \
    zlib1g-dev \
    """

  [build.platforms."linux/arm64".args]
    architecture = "arm64"

    sources = """
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main universe multiverse
    """

[run]
  description = "jammy for statically-linked applications containing tzdata and ca-certificates"
  dockerfile = "./run/run.Dockerfile"
  gid = 1000
  shell = "/sbin/nologin"
  uid = 1002

  [run.args]
    architecture = "amd64"

    sources = """
    deb http://archive.ubuntu.com/ubuntu jammy main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-security main universe multiverse
    """

    packages = """\
    ca-certificates \
    tzdata \
    """

  [run.platforms."linux/arm64".args]
    architecture = "arm64"

    sources = """
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main universe multiverse
    """